users:
  admin:
    name: Hamid Admin
    password: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918  # admin
    email: hamid_dx@outlook.com
  user1:
    name: Nick User
    password: 0a041b9462caa4a31bac3567e0b6e6fd9100787db2ab433d96f6d178cabfce90  # user123
    email: n.yafremau.mitsui@outlook.com

# Pre-authorized emails (optional)
preauthorized_emails:
  - a.shaat@mitsui.com