version: '3'

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: abc-xyz-dashboard
    ports:
      - "8501:8501"
      - "8502:8502"
    volumes:
      - ./:/app  # Mount the entire project directory
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: streamlit run app.py  # Set the default command to run your app