# User credentials 
[users.admin]
name = "Hamid Admin"
email = "hamid_dx@outlook.com"
password = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"  # SHA-256 hash of "admin"

[users.user1]
name = "Nick User"
email = "n.yafremau.mitsui@outlook.com"
password = "0a041b9462caa4a31bac3567e0b6e6fd9100787db2ab433d96f6d178cabfce90"  # SHA-256 hash of "user123"

# Pre-authorized emails (optional)
preauthorized_emails = ["a.shaat@mitsui.com"]